### ISSUE TITLE
some backgrounds not working

### ISSUE THREAD

**Issue by hakuchi** [systemed/potlatch2#122]
A lot of background layer in Potlatch2 are not working anymore.
Some of them worked some time ago, but after checked today they are no longer available or no longer working.     
Examples:
**Bavaria (2m)** and all **Erlangen Luftbild** - in [Germany](http://www.openstreetmap.org/edit?editor=potlatch2#map=19/49.59162/10.98840)
all **South Tyrol Orthofoto** and **South Tyrol Topomap** - in [Italy](http://www.openstreetmap.org/edit?editor=potlatch2#map=19/46.66478/11.09515)
**Japan GSI ortho Imagery**
a lot of backgrounds in **UK** - [link](http://www.openstreetmap.org/edit?editor=potlatch2#map=18/51.78643/-0.94211)
**Geoimage.at MaxRes** - in [Austria](http://www.openstreetmap.org/edit?editor=potlatch2#map=19/48.44138/15.01560). There was one working and one not working, but now is remaster only the non working in the list.
there can be a lot more.

for example the backgrounds from [Poland](http://www.openstreetmap.org/edit?editor=potlatch2#map=19/52.29448/20.71110), _basemap.at_ and _basemap.at Orthofoto_ in [Austia](http://www.openstreetmap.org/edit?editor=potlatch2#map=19/48.44138/15.01560) and the background from the [Philippines](http://www.openstreetmap.org/edit?editor=potlatch2#map=19/16.08244/120.44126) working.

I dont know if this is a error in the link, or if Potlatch2 is not compatible with the links or layer, but I think if one of them is working with **Potlatch2**, all of them should work, because on **iD** and **Josm** they are working.

**Comment by systemed** [comment]
P2 uses http://osmlab.github.io/editor-layer-index/imagery.json for its imagery list. Can you find the problematic entries in that list?

**Comment by hakuchi** [comment]
I checked some data in your link, and I think that Potlatch2 is not able to use `wms` or `wmts` because the background with `tms`(Poland, Philippines) working into the editor.

if I copy the **Geoimage.at** [tms link](http://geoimage.openstreetmap.at/4d80de696cd562a63ce463a58a61488d/$z/$x/$y.jpg) link by myself into the editor, I can see the background.
at the **Japan GSI ortho Imagery** I dont know why the above `tms` link is not working, but it works if I change the existing link to this: http://cyberjapandata.gsi.go.jp/xyz/ort/$z/$x/$y.jpg
the  **South Tyrol Orthofoto** and **South Tyrol Topomap** are not working in Potlatch2, because they are `wmts`.

Is there a way to make Potlatch able to read `wms`, `wmts` and `tms`?

**Comment by systemed** [comment]
P2 already supports tms but doesn't support wms or wmts, and I don't plan to add support (though, as ever, if someone were to come up with a pull request that would be lovely). I don't think iD supports either. The Japan GSI imagery seems to be working fine in P2, for example at http://www.openstreetmap.org/edit#map=18/37.72687/140.06247 .

**Comment by hakuchi** [comment]
I am not able to add a code to support wmts and wms in Potlatch2.

**Comment by systemed** [comment]
You may be able to use whoots to turn WMS/WMTS into TMS: http://whoots.mapwarper.net/

Closing as it's not something I plan to work on.
