### ISSUE TITLE
Add notes in the Readme (if relevant)

### ISSUE THREAD

**Issue by Binnette** [systemed/potlatch2#132]
Hi,

I have some questions, that other users may have. So can you please consider to improve the Readme file ?

Here are my questions:

1. Is this repo, the new repo of potlatch 2 ?
2. Is this version of potlatch installed on osm.org ?
3. Will you still continue to maintain it ?
4. Bonus question: i was teased by the 2020 grant to port potlatch2 to desktop. I think this is a REALLY good idea :+1: More editors prevent monopoly on one only editor/solution. Since the microgrant was not funded, will you still try to port it to desktop ?

Source: https://wiki.openstreetmap.org/wiki/Microgrants/Microgrants_2020/Proposal/Potlatch_2_for_desktop

Have a nice day :+1:

**Comment by systemed** [comment]
Work is underway on desktop Potlatch at the moment, funded by OSMF (separately to the microgrants). The first release will be later in November or early December, with lots more good stuff to come after that! It will probably be in this repo - watch this space.

**Comment by Binnette** [comment]
Thank for your answer @systemed :heart: 

BTW, it seems a good idea to me, that your first desktop version should be released as "3.x" version and not "2.x" version. :wink:

Have a nice day :+1: 
Please, feel free to ask me or the community to test the first alpha/beta version of the desktop version :+1:

**Comment by systemed** [comment]
Very very early Mac-only build here: https://www.systemed.net/potlatch/download

**Comment by Binnette** [comment]
Hi, 
I think I may have succeed installing Adobe Air on Ubuntu 20.40 by using aptitude to install ia32-libs and a bunch of 386 libs... I can run the 'Adobe AIR App installer". But when I pick the file "Potlatch.air", Adobe AIR display an error message telling me to update Adobe Air... but I already run the latest 2.6 Adobe Air Linux version. So I think that "Potlatch.air" needs Adobe AIR > 2.6.

So either see if you can provide "Potlatch.air" in Adobe AIR version 2.6 or maybe simply do not provide Potlatch on Linux, since Adobe don't support Linux anymore.

Have a nice day. :+1:

**Comment by systemed** [comment]
That's really useful - thanks!

Potlatch is expressly compiled to SWF version 11 which is equivalent to AIR 2.6 (https://stackoverflow.com/questions/9537076/chart-of-swf-versions-to-flash-versions). The only post-2.6 feature we use, as far as I know, is the native JSON decoding, and we fall back to a 2.6-compatible library if it's not available.

_However_, I guess it's possible that AIR is seeing that we're trying to pull in the native JSON decoding, and flaking out before we can fall back. I'll try and do an alternate build without the native JSON, and see if that's any better.

**Comment by Binnette** [comment]
Still on Ubuntu 20.04. Ok I was wrong. You can not install ia32-libs on Ubuntu 20.04 cause Ubuntu is amd64 and ia32libs is i386.
But you can still install "Adobe AIR" with the ".deb" file in amd64 version from here: http://update.devolo.com/linux/apt/pool/main/a/adobeair/

I downloaded some random ".air" file from Internet. But I can not get any to be installed with "Adobe Air app Installer".

Can you please consider sending me a "sample.air" file that just print "Hello World" and the version of the currently installed AIR runtime? It would be great if we can ensure that at least the "Adobe Air App Installer" is working.

Have a nice day :+1:

**Comment by Binnette** [comment]
I tested your early build on Windows 10. And it is working nicely 👍 
![image](https://user-images.githubusercontent.com/6597721/100378692-df12df80-3013-11eb-8ae4-b3c8340f9f1b.png)

I made a simple changeset with it: https://www.openstreetmap.org/changeset/94853036

**Comment by Binnette** [comment]
BTW, feel free to ask if you want to me to do other tests 👍  Windows 10 / Ubuntu 20.04
