### ISSUE TITLE
Potlatch_3_Windows__2020_12_07.zip under Wine, Unhandled page fault

### ISSUE THREAD

**Issue by SomeoneElseOSM** [systemed/potlatch2#135]
Not a huge amount to go on, but here goes anyway:

Ubuntu 18.04, up to date.
KDE
Wine64 from Ubuntu itself not the Wine PPA

wine64 ./Potlatch.exe 

gives, after a significant amount of editing (about 50 mins, https://www.openstreetmap.org/changeset/95733633):

wine: Unhandled page fault on read access to 0x00000000 at address 0x7bc4ece2 (thread 00fe), starting debugger...
00fe:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc4ece2

**Comment by SomeoneElseOSM** [comment]
Another example, same environment:

wine: Unhandled page fault on read access to 0x00000000 at address 0x7bc4ece2 (thread 0045), starting debugger...
0045:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc4ece2

**Comment by SomeoneElseOSM** [comment]
Another example, same environment:

wine: Unhandled page fault on write access to 0x00730059 at address 0x7bc4ef1e (thread 01b8), starting debugger...
01b8:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc4ef1e

(I was zooming in at the time that it disappeared)

**Comment by SomeoneElseOSM** [comment]
Another example, same environment (run by "wine64 Potlatch.exe"):

0069:fixme:secur32:schannel_get_mac_algid unknown algorithm 200, cipher 23
0091:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc4ef1e

(this time it was moving the imagery, not zooming, and the imagery was OS_OpenData_StreetView)

**Comment by SomeoneElseOSM** [comment]
and again, immediately after pasting a search location in after restart:

002c:err:clipboard:convert_selection Timed out waiting for SelectionNotify event
002b:fixme:imm:ImmReleaseContext (0x1005a, 0x5c74468): stub
wine: Unhandled page fault on read access to 0x07ac1ad4 at address 0x7bc4db47 (thread 007c), starting debugger...
007c:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc4db47

(although doing that immediately again didn't fail again)

**Comment by SomeoneElseOSM** [comment]
After another 39 minutes of use, a stacktrace:

https://map.atownsend.org.uk/tmp/backtrace_20201213_2005.txt

**Comment by mmd-osm** [comment]
These more or less random crashes are in line with what I've experienced in my tests (https://www.openstreetmap.org/user/Richard/diary/394825#comment48667). One the positive side, the initial P3 build was crashing more frequently than the current one does.

**Comment by systemed** [comment]
This is going to be a difficult/impossible one to track down - ultimately it's Wine not emulating things correctly, and unless we can pin down a particular set of circumstances that causes this to happen, it's something that can only be tackled on the Wine side.

I'm beginning to think that getting AIR 2.6 running on Linux is going to be easier than using Wine, so have created https://github.com/systemed/potlatch3/issues/2 to track it - there's a promising AIR installation there which I'd be delighted if someone can try.

**Comment by SomeoneElseOSM** [comment]
(not tested today's version yet but) I was definitely able to reduce crashes under Wine by "not doing anything until any background imagery has fully loaded".  I'll have a go with the latest version when I get a chance.

**Comment by SomeoneElseOSM** [comment]
Superseded by https://github.com/systemed/potlatch3/issues/5 (problems now occur much less often).
