### ISSUE TITLE
Potlatch_3_Windows_CPU__2020_12_07.zip under Wine, stack trace produced

### ISSUE THREAD

**Issue by SomeoneElseOSM** [systemed/potlatch2#138]
(for comparison with https://github.com/systemed/potlatch2/issues/135 which is the non-CPU version)

Ubuntu 18.04, up to date.
KDE
Wine64 from Ubuntu itself not the Wine PPA

wine64 Potlatch.exe

https://map.atownsend.org.uk/tmp/backtrace_20201213_2106.txt

**Comment by SomeoneElseOSM** [comment]
Try and run it again, I get

002c:err:clipboard:convert_selection Timed out waiting for SelectionNotify event
002b:fixme:imm:ImmReleaseContext (0x1005a, 0x6e689b0): stub
0065:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc4ebc4

immediately I try and search for 
https://www.openstreetmap.org/#map=19/54.25791/-1.24391

**Comment by SomeoneElseOSM** [comment]
Repeat the process, and it doesn't fail, especially if I make sure to wait for all imagery to load after a map drag, and try and avoid zooming in or out via the mouse wheel.

**Comment by systemed** [comment]
Oddly "convert_selection Timed out waiting for SelectionNotify event" appears to be clipboard-related, and P3 doesn't use the clipboard so I'm not sure what's going on there.

**Comment by SomeoneElseOSM** [comment]
I've not seen this issue with the latest build at all (despite trying to provoke it).  See https://github.com/systemed/potlatch3/issues/5 for current issues.
